apiVersion: v1
kind: Service
metadata:
  name: tripblip-backend
spec:
  selector:
    app: tripblip-backend
    color: blue
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: tripblip-pyagent
spec:
  selector:
    app: tripblip-pyagent
    color: blue
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP

